# Generated by Django 4.1.3 on 2023-11-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_household'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='q1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='household',
            name='q10',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='household',
            name='q11',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='household',
            name='q12',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='household',
            name='q13',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='household',
            name='q2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='household',
            name='q3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='household',
            name='q4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='household',
            name='q5',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='household',
            name='q6',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='household',
            name='q7',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='household',
            name='q8',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='household',
            name='q9',
            field=models.FloatField(),
        ),
    ]
