# Generated by Django 4.1.3 on 2023-11-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_alter_household_q1_alter_household_q10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='mpi',
            field=models.FloatField(default=0.0),
        ),
    ]
