# Generated by Django 4.1.3 on 2023-12-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_household_mpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_admin', models.CharField(max_length=255)),
                ('issue', models.EmailField(max_length=254)),
                ('messages', models.TextField()),
            ],
        ),
    ]
