# Generated by Django 4.1.3 on 2023-12-03 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_contact_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 3, 10, 6, 41, 720173, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
