# Generated by Django 4.1.3 on 2023-12-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_contact_submission_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='household_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('c_number', models.IntegerField(max_length=255)),
                ('dt_result', models.CharField(default='', max_length=255)),
                ('svm_result', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
