# Generated by Django 4.1.3 on 2023-12-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_household_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household_profile',
            name='c_number',
            field=models.IntegerField(),
        ),
    ]
