# Generated by Django 4.1.3 on 2023-12-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_alter_household_profile_c_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='mpi',
        ),
        migrations.AddField(
            model_name='household_profile',
            name='mpi',
            field=models.FloatField(default=0.0),
        ),
    ]
