# Generated by Django 4.1.3 on 2023-12-05 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_alter_household_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
