# Generated by Django 4.1.3 on 2023-12-05 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0013_alter_household_profile_c_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household_profile',
            name='c_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(11)]),
        ),
    ]
