# Generated by Django 4.1.3 on 2023-12-05 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_alter_household_profile_dt_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household_profile',
            name='c_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
