# Generated by Django 4.1.3 on 2023-12-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0021_result_classify_remove_household_profile_dt_result_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='id',
            new_name='unique_id',
        ),
        migrations.RenameField(
            model_name='household_profile',
            old_name='id',
            new_name='unique_id',
        ),
        migrations.RenameField(
            model_name='result_classify',
            old_name='id',
            new_name='unique_id',
        ),
    ]
