# Generated by Django 4.1.3 on 2023-12-05 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0022_rename_id_household_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='unique_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='household_profile',
            name='unique_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='interface.household'),
        ),
        migrations.AlterField(
            model_name='result_classify',
            name='unique_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='interface.household'),
        ),
    ]
