# Generated by Django 4.1.3 on 2023-12-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0023_alter_household_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household_profile',
            name='unique_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='result_classify',
            name='unique_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
