# Generated by Django 4.1.3 on 2023-12-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0024_alter_household_profile_unique_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='unique_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='household_profile',
            old_name='unique_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='result_classify',
            old_name='unique_id',
            new_name='id',
        ),
    ]
