# Generated by Django 4.1.3 on 2023-12-06 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0026_alter_household_id_alter_household_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household_profile',
            name='user_email',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
