# Generated by Django 4.1.3 on 2023-12-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0027_alter_household_profile_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='household_profile',
            name='user_number',
            field=models.FloatField(default=0.0),
        ),
    ]
