# Generated by Django 4.1.3 on 2023-12-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0028_household_profile_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household_profile',
            name='user_number',
            field=models.CharField(max_length=255),
        ),
    ]
