# Generated by Django 4.1.3 on 2023-12-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0029_alter_household_profile_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='household_profile',
            name='user_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
