# Generated by Django 4.1.3 on 2023-12-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0030_household_profile_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='q1',
            new_name='indi1',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='q10',
            new_name='indi10',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='q11',
            new_name='indi11',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='q12',
            new_name='indi12',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='q13',
            new_name='indi13',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='q2',
            new_name='indi2',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='q3',
            new_name='indi3',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='q4',
            new_name='indi4',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='q5',
            new_name='indi5',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='q6',
            new_name='indi6',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='q7',
            new_name='indi7',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='q8',
            new_name='indi8',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='q9',
            new_name='indi9',
        ),
    ]
