# Generated by Django 4.1.3 on 2023-12-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0033_householdprofile_resultmpi_delete_household_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdprofile',
            name='mpi',
        ),
        migrations.AlterField(
            model_name='resultmpi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
